language: go
go:
  - 1.9.x
  - master
install:
  - curl https://glide.sh/get | sh
  - glide i
  - rm -rf ./vendor/github.com/hashicorp/serf/vendor
  - mkdir dist
script:
  - go build -i -o ./dist/djob .