sudo: required

language: go

service:
  - docker
  - mysql

go:
  - 1.9.x
  - master

before_install:
- docker run -d -p 4000:4000 tidb
- docker run -d -p 2379:2379 quay.io/coreos/etcd:v2.3.8
- mysql -h127.0.0.1 -P4000 -e 'create database djob;'

install:
  - curl https://glide.sh/get | sh
  - glide i
  - rm -rf ./vendor/github.com/hashicorp/serf/vendor
  - mkdir dist
script:
  - go build -i -o ./dist/djob .