// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	api.proto
	job.proto
	serfQueryParams.proto

It has these top-level messages:
	RespJob
	Params
	Job
	JobStatus
	Execution
	Result
	NewJobQueryParams
	RunJobQueryParams
	GetRPCConfigResp
	JobCountResp
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RespJob struct {
	Status  int32  `protobuf:"varint,1,opt,name=Status" json:"Status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	Data    []*Job `protobuf:"bytes,3,rep,name=Data" json:"Data,omitempty"`
}

func (m *RespJob) Reset()                    { *m = RespJob{} }
func (m *RespJob) String() string            { return proto.CompactTextString(m) }
func (*RespJob) ProtoMessage()               {}
func (*RespJob) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RespJob) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RespJob) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RespJob) GetData() []*Job {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RespJob)(nil), "message.RespJob")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0xe2,
	0xcc, 0xca, 0x4f, 0x82, 0x88, 0x29, 0xc5, 0x72, 0xb1, 0x07, 0xa5, 0x16, 0x17, 0x78, 0xe5, 0x27,
	0x09, 0x89, 0x71, 0xb1, 0x05, 0x97, 0x24, 0x96, 0x94, 0x16, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0xb0,
	0x06, 0x41, 0x79, 0x42, 0x12, 0x5c, 0xec, 0xbe, 0x10, 0x8d, 0x12, 0x4c, 0x40, 0x09, 0xce, 0x20,
	0x18, 0x57, 0x48, 0x81, 0x8b, 0xc5, 0x25, 0xb1, 0x24, 0x51, 0x82, 0x59, 0x81, 0x59, 0x83, 0xdb,
	0x88, 0x47, 0x0f, 0x6a, 0xbe, 0x1e, 0xd0, 0xb4, 0x20, 0xb0, 0x4c, 0x12, 0x1b, 0xd8, 0x16, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0x2d, 0x95, 0xd3, 0x86, 0x00, 0x00, 0x00,
}
