// Code generated by protoc-gen-go.
// source: serfQueryParams.proto
// DO NOT EDIT!

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NewJobQueryParams struct {
	Name   string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Region string `protobuf:"bytes,2,opt,name=Region" json:"Region,omitempty"`
}

func (m *NewJobQueryParams) Reset()                    { *m = NewJobQueryParams{} }
func (m *NewJobQueryParams) String() string            { return proto.CompactTextString(m) }
func (*NewJobQueryParams) ProtoMessage()               {}
func (*NewJobQueryParams) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *NewJobQueryParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewJobQueryParams) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type RunJobQueryParams struct {
	Name              string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	SchedulerNodename string `protobuf:"bytes,2,opt,name=SchedulerNodename" json:"SchedulerNodename,omitempty"`
}

func (m *RunJobQueryParams) Reset()                    { *m = RunJobQueryParams{} }
func (m *RunJobQueryParams) String() string            { return proto.CompactTextString(m) }
func (*RunJobQueryParams) ProtoMessage()               {}
func (*RunJobQueryParams) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *RunJobQueryParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RunJobQueryParams) GetSchedulerNodename() string {
	if m != nil {
		return m.SchedulerNodename
	}
	return ""
}

func init() {
	proto.RegisterType((*NewJobQueryParams)(nil), "message.NewJobQueryParams")
	proto.RegisterType((*RunJobQueryParams)(nil), "message.RunJobQueryParams")
}

func init() { proto.RegisterFile("serfQueryParams.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x4e, 0x2d, 0x4a,
	0x0b, 0x2c, 0x4d, 0x2d, 0xaa, 0x0c, 0x48, 0x2c, 0x4a, 0xcc, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0xb2, 0xe7, 0x12, 0xf4, 0x4b,
	0x2d, 0xf7, 0xca, 0x4f, 0x42, 0x52, 0x23, 0x24, 0xc4, 0xc5, 0xe2, 0x97, 0x98, 0x9b, 0x2a, 0xc1,
	0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x0b, 0x89, 0x71, 0xb1, 0x05, 0xa5, 0xa6, 0x67, 0xe6,
	0xe7, 0x49, 0x30, 0x81, 0x45, 0xa1, 0x3c, 0xa5, 0x50, 0x2e, 0xc1, 0xa0, 0xd2, 0x3c, 0x22, 0x0c,
	0xd0, 0xe1, 0x12, 0x0c, 0x4e, 0xce, 0x48, 0x4d, 0x29, 0xcd, 0x49, 0x2d, 0xf2, 0xcb, 0x4f, 0x49,
	0xcd, 0x03, 0x29, 0x80, 0x98, 0x85, 0x29, 0x91, 0xc4, 0x06, 0x76, 0xa7, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x60, 0xb3, 0xdf, 0x52, 0xc0, 0x00, 0x00, 0x00,
}
