// Code generated by protoc-gen-go.
// source: serfQueryParams.proto
// DO NOT EDIT!

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NewJobQueryParams struct {
	Name           string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Region         string `protobuf:"bytes,2,opt,name=Region" json:"Region,omitempty"`
	SourceNodeName string `protobuf:"bytes,3,opt,name=SourceNodeName" json:"SourceNodeName,omitempty"`
}

func (m *NewJobQueryParams) Reset()                    { *m = NewJobQueryParams{} }
func (m *NewJobQueryParams) String() string            { return proto.CompactTextString(m) }
func (*NewJobQueryParams) ProtoMessage()               {}
func (*NewJobQueryParams) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *NewJobQueryParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewJobQueryParams) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *NewJobQueryParams) GetSourceNodeName() string {
	if m != nil {
		return m.SourceNodeName
	}
	return ""
}

type RunJobQueryParams struct {
	Name              string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	SchedulerNodename string `protobuf:"bytes,2,opt,name=SchedulerNodename" json:"SchedulerNodename,omitempty"`
}

func (m *RunJobQueryParams) Reset()                    { *m = RunJobQueryParams{} }
func (m *RunJobQueryParams) String() string            { return proto.CompactTextString(m) }
func (*RunJobQueryParams) ProtoMessage()               {}
func (*RunJobQueryParams) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *RunJobQueryParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RunJobQueryParams) GetSchedulerNodename() string {
	if m != nil {
		return m.SchedulerNodename
	}
	return ""
}

type GetRPCConfigResp struct {
	Ip   string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *GetRPCConfigResp) Reset()                    { *m = GetRPCConfigResp{} }
func (m *GetRPCConfigResp) String() string            { return proto.CompactTextString(m) }
func (*GetRPCConfigResp) ProtoMessage()               {}
func (*GetRPCConfigResp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *GetRPCConfigResp) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *GetRPCConfigResp) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type JobCountResp struct {
	Name  string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=Count" json:"Count,omitempty"`
}

func (m *JobCountResp) Reset()                    { *m = JobCountResp{} }
func (m *JobCountResp) String() string            { return proto.CompactTextString(m) }
func (*JobCountResp) ProtoMessage()               {}
func (*JobCountResp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *JobCountResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobCountResp) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*NewJobQueryParams)(nil), "message.NewJobQueryParams")
	proto.RegisterType((*RunJobQueryParams)(nil), "message.RunJobQueryParams")
	proto.RegisterType((*GetRPCConfigResp)(nil), "message.GetRPCConfigResp")
	proto.RegisterType((*JobCountResp)(nil), "message.JobCountResp")
}

func init() { proto.RegisterFile("serfQueryParams.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x90, 0x3f, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0xb9, 0x3b, 0xef, 0xc4, 0x41, 0x0e, 0xb3, 0xa8, 0x5c, 0x29, 0x5b, 0x88, 0x85, 0xd8,
	0x08, 0x62, 0x9f, 0x42, 0xb0, 0x08, 0x71, 0x83, 0x1f, 0x60, 0x93, 0x4c, 0xd6, 0x80, 0xd9, 0x59,
	0xf6, 0x0f, 0xe2, 0xb7, 0x37, 0x99, 0xa4, 0x10, 0xb5, 0xb0, 0x7b, 0x33, 0xf3, 0x7e, 0xf3, 0x86,
	0x81, 0x8b, 0x80, 0xbe, 0x7b, 0x49, 0xe8, 0x3f, 0x4b, 0xed, 0xf5, 0x10, 0xee, 0x9c, 0xa7, 0x48,
	0xe2, 0x78, 0xc0, 0x10, 0xb4, 0x41, 0x69, 0x20, 0x2b, 0xf0, 0xe3, 0x99, 0xea, 0x6f, 0x1e, 0x21,
	0xe0, 0xa8, 0xd0, 0x03, 0x1e, 0x56, 0x57, 0xab, 0x9b, 0x13, 0xc5, 0x5a, 0x5c, 0xc2, 0x4e, 0xa1,
	0xe9, 0xc9, 0x1e, 0xd6, 0xdc, 0x5d, 0x2a, 0x71, 0x0d, 0xfb, 0x8a, 0x92, 0x6f, 0xb0, 0xa0, 0x16,
	0x99, 0xda, 0xf0, 0xfc, 0x47, 0x57, 0xbe, 0x42, 0xa6, 0x92, 0xfd, 0x47, 0xd0, 0x2d, 0x64, 0x55,
	0xf3, 0x86, 0x6d, 0x7a, 0x47, 0x3f, 0xd1, 0x76, 0x32, 0xcc, 0x99, 0xbf, 0x07, 0xf2, 0x01, 0xce,
	0x9e, 0x30, 0xaa, 0x32, 0xcf, 0xc9, 0x76, 0xbd, 0x51, 0x18, 0x9c, 0xd8, 0xc3, 0xba, 0x77, 0xcb,
	0xce, 0x51, 0x4d, 0x29, 0x8e, 0x7c, 0xe4, 0x25, 0x5b, 0xc5, 0x5a, 0x3e, 0xc2, 0xe9, 0x78, 0x4b,
	0x4e, 0xc9, 0x46, 0x66, 0xfe, 0xba, 0xe4, 0x1c, 0xb6, 0x6c, 0x60, 0x70, 0xa3, 0xe6, 0xa2, 0xde,
	0xf1, 0x07, 0xef, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xf5, 0xa0, 0xf5, 0x5a, 0x01, 0x00,
	0x00,
}
