// Code generated by protoc-gen-go.
// source: message/serfQueryParams.proto
// DO NOT EDIT!

package message

import "github.com/golang/protobuf/proto"
import "fmt"
import "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type JobQueryParams struct {
	Name           string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Region         string `protobuf:"bytes,2,opt,name=Region" json:"Region,omitempty"`
	SourceNodeName string `protobuf:"bytes,3,opt,name=SourceNodeName" json:"SourceNodeName,omitempty"`
	DistNodeName   string `protobuf:"bytes,4,opt,name=DistNodeName" json:"DistNodeName,omitempty"`
}

func (m *JobQueryParams) Reset()                    { *m = JobQueryParams{} }
func (m *JobQueryParams) String() string            { return proto.CompactTextString(m) }
func (*JobQueryParams) ProtoMessage()               {}
func (*JobQueryParams) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *JobQueryParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobQueryParams) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *JobQueryParams) GetSourceNodeName() string {
	if m != nil {
		return m.SourceNodeName
	}
	return ""
}

func (m *JobQueryParams) GetDistNodeName() string {
	if m != nil {
		return m.DistNodeName
	}
	return ""
}

type GetRPCConfigResp struct {
	Ip   string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *GetRPCConfigResp) Reset()                    { *m = GetRPCConfigResp{} }
func (m *GetRPCConfigResp) String() string            { return proto.CompactTextString(m) }
func (*GetRPCConfigResp) ProtoMessage()               {}
func (*GetRPCConfigResp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *GetRPCConfigResp) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *GetRPCConfigResp) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type JobCountResp struct {
	Name  string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=Count" json:"Count,omitempty"`
}

func (m *JobCountResp) Reset()                    { *m = JobCountResp{} }
func (m *JobCountResp) String() string            { return proto.CompactTextString(m) }
func (*JobCountResp) ProtoMessage()               {}
func (*JobCountResp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *JobCountResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobCountResp) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type QueryResult struct {
	Status  int32  `protobuf:"varint,1,opt,name=Status" json:"Status,omitempty"`
	Node    string `protobuf:"bytes,2,opt,name=Node" json:"Node,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=Message" json:"Message,omitempty"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *QueryResult) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *QueryResult) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *QueryResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type QueryJobRunParams struct {
	Execution *Execution `protobuf:"bytes,1,opt,name=Execution" json:"Execution,omitempty"`
	Exp       string     `protobuf:"bytes,2,opt,name=exp" json:"exp,omitempty"`
}

func (m *QueryJobRunParams) Reset()                    { *m = QueryJobRunParams{} }
func (m *QueryJobRunParams) String() string            { return proto.CompactTextString(m) }
func (*QueryJobRunParams) ProtoMessage()               {}
func (*QueryJobRunParams) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *QueryJobRunParams) GetExecution() *Execution {
	if m != nil {
		return m.Execution
	}
	return nil
}

func (m *QueryJobRunParams) GetExp() string {
	if m != nil {
		return m.Exp
	}
	return ""
}

func init() {
	proto.RegisterType((*JobQueryParams)(nil), "message.JobQueryParams")
	proto.RegisterType((*GetRPCConfigResp)(nil), "message.GetRPCConfigResp")
	proto.RegisterType((*JobCountResp)(nil), "message.JobCountResp")
	proto.RegisterType((*QueryResult)(nil), "message.QueryResult")
	proto.RegisterType((*QueryJobRunParams)(nil), "message.QueryJobRunParams")
}

func init() { proto.RegisterFile("message/serfQueryParams.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x4d, 0xd3, 0xd2, 0x69, 0x09, 0xed, 0x22, 0x12, 0x04, 0x41, 0xf6, 0x20, 0x9e, 0xa2,
	0x28, 0x88, 0xf7, 0x28, 0x82, 0x60, 0xa9, 0x9b, 0x83, 0xe7, 0xa4, 0x4e, 0x43, 0xc4, 0x64, 0xc3,
	0x7e, 0x40, 0xfd, 0x07, 0xfe, 0x6c, 0x93, 0xc9, 0xb6, 0x7e, 0xd0, 0xdb, 0x9b, 0x99, 0xf7, 0x66,
	0xdf, 0x9b, 0x85, 0xd3, 0x0a, 0xb5, 0xce, 0x0a, 0xbc, 0xd4, 0xa8, 0x36, 0x2f, 0x16, 0xd5, 0xe7,
	0x2a, 0x53, 0x59, 0xa5, 0xe3, 0x46, 0x49, 0x23, 0xd9, 0xd8, 0x8d, 0x4f, 0x16, 0x3b, 0xde, 0xbb,
	0xcc, 0xfb, 0x19, 0xff, 0xf2, 0x20, 0x7c, 0x92, 0xf9, 0x2f, 0x11, 0x63, 0x30, 0x5c, 0x66, 0x15,
	0x46, 0xde, 0x99, 0x77, 0x31, 0x11, 0x84, 0xd9, 0x31, 0x8c, 0x04, 0x16, 0xa5, 0xac, 0xa3, 0x01,
	0x75, 0x5d, 0xc5, 0xce, 0x21, 0x4c, 0xa5, 0x55, 0x6b, 0x5c, 0xca, 0x37, 0x24, 0x95, 0x4f, 0xf3,
	0x7f, 0x5d, 0xc6, 0x61, 0x76, 0x5f, 0x6a, 0xb3, 0x67, 0x0d, 0x89, 0xf5, 0xa7, 0xc7, 0x6f, 0x61,
	0xfe, 0x88, 0x46, 0xac, 0x92, 0x44, 0xd6, 0x9b, 0xb2, 0x10, 0xa8, 0x1b, 0x16, 0xc2, 0xa0, 0x6c,
	0x9c, 0x93, 0x16, 0x75, 0xde, 0x1a, 0xa9, 0x0c, 0xb9, 0x08, 0x04, 0x61, 0x7e, 0x07, 0xb3, 0x36,
	0x41, 0x22, 0x6d, 0x6d, 0x48, 0x73, 0xc8, 0xff, 0x11, 0x04, 0x44, 0x20, 0xa1, 0x2f, 0xfa, 0x82,
	0xa7, 0x30, 0xa5, 0xe0, 0xad, 0xcc, 0x7e, 0x98, 0x2e, 0x64, 0x6a, 0x32, 0x63, 0x35, 0x49, 0x03,
	0xe1, 0x2a, 0x5a, 0xd8, 0x9a, 0x74, 0xd1, 0x09, 0xb3, 0x08, 0xc6, 0xcf, 0xfd, 0x31, 0x5d, 0xe2,
	0x5d, 0xc9, 0x5f, 0x61, 0x41, 0x4b, 0x5b, 0x4f, 0xc2, 0xd6, 0xee, 0xa6, 0x57, 0x30, 0x79, 0xd8,
	0xe2, 0xda, 0x9a, 0xee, 0x84, 0xdd, 0xf6, 0xe9, 0x35, 0x8b, 0xdd, 0x6f, 0xc4, 0xfb, 0x89, 0xf8,
	0x21, 0xb1, 0x39, 0xf8, 0xb8, 0x6d, 0xdc, 0x9b, 0x1d, 0xcc, 0x47, 0xf4, 0x63, 0x37, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xc6, 0x6e, 0x53, 0x39, 0xee, 0x01, 0x00, 0x00,
}
